# https://taskfile.dev

version: '3'

vars:
  PROJECT: excuses

tasks:

  default:
    cmds:
      - ng serve
    silent: true

  push:
    desc: commit and pushes current changes
    cmds:
      - git add .  || true
      - git commit -am "a" || true
      - git push || true

  deploy:
    desc: deploy
    cmds:
      - ng build
      - tar cfz dist.tgz dist/ngx-excuses/browser
      - scp dist.tgz $REMOTE_HOST:/var/www/{{.PROJECT}}
      - ssh $REMOTE_HOST rm -rf /var/www/{{.PROJECT}}/dist
      - ssh $REMOTE_HOST tar zxf /var/www/{{.PROJECT}}/dist.tgz --directory /var/www/{{.PROJECT}}
      - ssh $REMOTE_HOST rm /var/www/{{.PROJECT}}/dist.tgz